version: '3'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: python-web:v1
#    container_name: python-web
#    ports:
#     - 8080:5000
#    volumes:
#     - ~/webProjects:/code
#    command: ["cd", "/code/flask_starlight"]
#    command: ["python", "auto_app.py"]
#    depends_on:
#     - mysql
#     - redis
#     - rabbitmq
#     - elasticsearch
#     - nginx

#  mysql:
#    image: mysql:latest
#    container_name: mysql-web
#    volumes:
#      - ~/mysql/data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root1234
#    ports:
#      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis-web
    ports:
      - 6379:6379
    volumes:
      - ~/redis/data:/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-web
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=developer
      - RABBITMQ_DEFAULT_PASS=dev1234
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: elasticsearch:5-alpine
    restart: always
    container_name: elasticsearch-web
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m -XX:+AssumeMP"

  nginx:
    image: nginx
    container_name: nginx-web
    volumes:
      - /root/nginx:/etc/nginx
      - /root/webProjects/hexo_blog/public:/root/blog/public
      - ~/webProjects:/web
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
