"""empty message

Revision ID: 89bc5a7aa5ce
Revises: c4a059e70386
Create Date: 2018-12-24 21:18:17.895729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bc5a7aa5ce'
down_revision = 'c4a059e70386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('ordering', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('update_time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('ordering', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'ordering')
    op.drop_column('users', 'create_time')
    op.drop_column('roles', 'update_time')
    op.drop_column('roles', 'ordering')
    op.drop_column('roles', 'create_time')
    # ### end Alembic commands ###
